### ISSUE TITLE
DoesNotExist: DocumentTypeRule has no doccodepluginmapping.

### ISSUE THREAD

**Issue by chhantyal** [adlibre/Adlibre-DMS#12]
Sorry for raising another issue, I will tinker myself it I can find way.
 I am having hard time setting it up. I get following error after installing fixtures.

````
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/neo/projects/Adlibre-DMS/dms/lib/python2.7/site-packages/Django-1.6.2-py2.7.egg/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/Users/neo/projects/Adlibre-DMS/dms/lib/python2.7/site-packages/Django-1.6.2-py2.7.egg/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/Users/neo/projects/Adlibre-DMS/dms/lib/python2.7/site-packages/Django-1.6.2-py2.7.egg/django/template/response.py", line 81, in rendered_content
    context = self.resolve_context(self.context_data)
  File "/Users/neo/projects/Adlibre-DMS/dms/lib/python2.7/site-packages/Django-1.6.2-py2.7.egg/django/template/response.py", line 159, in resolve_context
    return RequestContext(self._request, context, current_app=self._current_app)
  File "/Users/neo/projects/Adlibre-DMS/dms/lib/python2.7/site-packages/Django-1.6.2-py2.7.egg/django/template/context.py", line 169, in __init__
    self.update(processor(request))
  File "/Users/neo/projects/Adlibre-DMS/adlibre_dms/context_processors.py", line 40, in uncategorized
    dmid = str(conf.uncategorized.doccodepluginmapping.pk)
  File "/Users/neo/projects/Adlibre-DMS/dms/lib/python2.7/site-packages/Django-1.6.2-py2.7.egg/django/db/models/fields/related.py", line 206, in __get__
    self.related.get_accessor_name()))
DoesNotExist: DocumentTypeRule has no doccodepluginmapping.
[23/Sep/2015 23:48:15] "GET / HTTP/1.1" 500 105601
````

**Comment by garmoncheg** [comment]
Seems like you have not properly installed the fixtures. 
How did this happen? Which steps precede this message?
how did you install the provided fixtures?

**Comment by chhantyal** [comment]
Hi, 

This is working after I installed all fixtures with .json extensions here https://github.com/adlibre/Adlibre-DMS/tree/master/fixtures

Thanks.
